version: '3'

services:
  web:
    build: './web'
    environment: 
      - APACHE_RUN_USER=www-data
    volumes: 
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports: 
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: englitopia
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5080:8080