version: '3'

services:
  server:
    build: serhiicho/englitopia:server
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 80:80
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    # build: ./db
    image: serhiicho/englitopia:db
    restart: always
    volumes:
      - ./db/storage:/var/lib/mysql